### ISSUE TITLE
5k generator python script

### ISSUE THREAD

**Issue by HeinLarsen** [code-cafes/cph#11]
**Problem**
I've made a little script in python used to easily create repositories, setup our Circle Ci config, clone github repositories for use as a template or theme and so on. But I'm unsure if i've used the best methods to create this script.
**solution**
Lets go through the code and see whats being done and how we can optimize it so it runs more efficient.
**value**
A faster and more efficient script.

**Comment by lakruzz** [comment]
@sygdrome I'm closing this one - that's correct eh?

**Comment by HeinLarsen** [comment]
@lakruzz That's fine with me
