### ISSUE TITLE
Welcome - CoDe Cafe March 17

### ISSUE THREAD

**Issue by carolineolivia** [code-cafes/cph#18]
Hi CoDe Café participants

Say hello to the team! 

Simple leave a comment here in this issue.

**Comment by lakruzz** [comment]
Hi everyone - There's a new README in this repo, please read up and prepare yourselves for tomorrow.

**Comment by lakruzz** [comment]
We're here: https://meet.google.com/qat-zcen-omd

**Comment by groenborg** [comment]
Hello everyone
I didn't get a ticket for today, but if there is room for one more hand somewhere I would love to join in.
